// <auto-generated />
using FIlmoviEFApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FIlmoviEFApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FIlmoviEFApi.Models.Filmovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReziserId")
                        .HasColumnType("int");

                    b.Property<string>("Zanr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReziserId");

                    b.ToTable("Filmovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Godina = 1985,
                            Ime = "neki film",
                            ReziserId = 2,
                            Zanr = "Komedija"
                        },
                        new
                        {
                            Id = 2,
                            Godina = 1985,
                            Ime = "neki drugi film",
                            ReziserId = 3,
                            Zanr = "Horor"
                        },
                        new
                        {
                            Id = 3,
                            Godina = 1985,
                            Ime = "neki treci film",
                            ReziserId = 5,
                            Zanr = "Komedija"
                        },
                        new
                        {
                            Id = 4,
                            Godina = 1985,
                            Ime = "neki cetvrti film",
                            ReziserId = 4,
                            Zanr = "Komedija"
                        },
                        new
                        {
                            Id = 5,
                            Godina = 1985,
                            Ime = "neki peti film",
                            ReziserId = 1,
                            Zanr = "Komedija"
                        });
                });

            modelBuilder.Entity("FIlmoviEFApi.Models.Reziser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Starost")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reziseri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ime = "Christopher",
                            Prezime = "Nolan",
                            Starost = 50
                        },
                        new
                        {
                            Id = 2,
                            Ime = "Quentin",
                            Prezime = "Tarantino",
                            Starost = 58
                        },
                        new
                        {
                            Id = 3,
                            Ime = "Steven",
                            Prezime = "Spielberg",
                            Starost = 75
                        },
                        new
                        {
                            Id = 4,
                            Ime = "Martin",
                            Prezime = "Scorsese",
                            Starost = 79
                        },
                        new
                        {
                            Id = 5,
                            Ime = "David",
                            Prezime = "Fincher",
                            Starost = 59
                        });
                });

            modelBuilder.Entity("FIlmoviEFApi.Models.Filmovi", b =>
                {
                    b.HasOne("FIlmoviEFApi.Models.Reziser", "Reziser")
                        .WithMany()
                        .HasForeignKey("ReziserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reziser");
                });
#pragma warning restore 612, 618
        }
    }
}
